#!/bin/sh
    
echo "  db:
    image: postgres:alpine
    restart: always
    tty: false
    ports:
        - 5432:5432
    environment:
        - PGDATA=/var/lib/postgres/data
    env_file:
        - ./docker/db/db.env
    volumes:
        - database:/var/lib/postgres/data\n" >> docker-compose.yaml