INSERT INTO notice_source
  (code, name, url, created)
VALUES
  ('adium', 'Adium', 'http://www.adiumx.com/', CURRENT_TIMESTAMP),
  ('Afficheur', 'Afficheur', 'http://afficheur.sourceforge.jp/', CURRENT_TIMESTAMP),
  ('AgentSolo.com','AgentSolo.com','http://www.agentsolo.com/', CURRENT_TIMESTAMP),
  ('anyio', 'Any.IO', 'http://any.io/', CURRENT_TIMESTAMP),
  ('betwittered','BeTwittered','http://www.32hours.com/betwitteredinfo/', CURRENT_TIMESTAMP),
  ('bti','bti','http://gregkh.github.com/bti/', CURRENT_TIMESTAMP),
  ('choqok', 'Choqok', 'http://choqok.gnufolks.org/', CURRENT_TIMESTAMP),
  ('cliqset', 'Cliqset', 'http://www.cliqset.com/', CURRENT_TIMESTAMP),
  ('DarterosStatus', 'Darteros Status', 'http://www.darteros.com/doc/Darteros_Status', CURRENT_TIMESTAMP),
  ('deskbar','Deskbar-Applet','http://www.gnome.org/projects/deskbar-applet/', CURRENT_TIMESTAMP),
  ('Do','Gnome Do','http://do.davebsd.com/wiki/index.php?title=Microblog_Plugin', CURRENT_TIMESTAMP),
  ('drupal','Drupal','http://drupal.org/', CURRENT_TIMESTAMP),
  ('eventbox','EventBox','http://thecosmicmachine.com/eventbox/', CURRENT_TIMESTAMP),
  ('identica-mode','Emacs Identica-mode','http://nongnu.org/identica-mode/', CURRENT_TIMESTAMP),
  ('Facebook','Facebook','http://apps.facebook.com/identica/', CURRENT_TIMESTAMP),
  ('feed2omb','feed2omb','http://projects.ciarang.com/p/feed2omb/', CURRENT_TIMESTAMP),
  ('get2gnow', 'get2gnow', 'http://uberchicgeekchick.com/?projects=get2gnow', CURRENT_TIMESTAMP),
  ('gNewBook', 'gNewBook', 'http://www.gnewbook.org/', CURRENT_TIMESTAMP),
  ('gravity', 'Gravity', 'http://mobileways.de/gravity', CURRENT_TIMESTAMP),
  ('Gwibber','Gwibber','http://launchpad.net/gwibber', CURRENT_TIMESTAMP),
  ('HelloTxt','HelloTxt','http://hellotxt.com/', CURRENT_TIMESTAMP),
  ('identicatools','Laconica Tools','http://bitbucketlabs.net/laconica-tools/', CURRENT_TIMESTAMP),
  ('identichat','identichat','http://identichat.prosody.im/', CURRENT_TIMESTAMP),
  ('IdentiCurse','IdentiCurse','http://identicurse.net/', CURRENT_TIMESTAMP),
  ('IdentiFox','IdentiFox','http://www.bitbucket.org/uncryptic/identifox/', CURRENT_TIMESTAMP),
  ('identitwitch','IdentiTwitch','http://richfish.org/identitwitch/', CURRENT_TIMESTAMP),
  ('Jiminy','Jiminy','', CURRENT_TIMESTAMP),
  ('LaTwit','LaTwit','http://latwit.mac65.com/', CURRENT_TIMESTAMP),
  ('LiveTweeter', 'LiveTweeter', 'http://addons.songbirdnest.com/addon/1204', CURRENT_TIMESTAMP),
  ('livetweeter', 'livetweeter', 'http://addons.songbirdnest.com/addon/1204', CURRENT_TIMESTAMP),
  ('maisha', 'Maisha', 'http://maisha.grango.org/', CURRENT_TIMESTAMP),
  ('mbpidgin','mbpidgin','', CURRENT_TIMESTAMP),
  ('Mobidentica', 'Mobidentica', 'http://www.substanceofcode.com/software/mobidentica/', CURRENT_TIMESTAMP),
  ('moconica','Moconica','http://moconica.com/', CURRENT_TIMESTAMP),
  ('mustard', 'mustard', 'http://mustard.macno.org', CURRENT_TIMESTAMP),
  ('nambu','Nambu','http://www.nambu.com/', CURRENT_TIMESTAMP),
  ('peoplebrowsr', 'PeopleBrowsr', 'http://www.peoplebrowsr.com/', CURRENT_TIMESTAMP),
  ('Pikchur','Pikchur','http://www.pikchur.com/', CURRENT_TIMESTAMP),
  ('Ping.fm','Ping.fm','http://ping.fm/', CURRENT_TIMESTAMP),
  ('pingvine','PingVine','http://pingvine.com/', CURRENT_TIMESTAMP),
  ('pocketwit','PockeTwit','', CURRENT_TIMESTAMP),
  ('posty','Posty','http://spreadingfunkyness.com/posty/', CURRENT_TIMESTAMP),
  ('qtwitter','qTwitter','http://qtwitter.ayoy.net/', CURRENT_TIMESTAMP),
  ('qwit', 'Qwit', '', CURRENT_TIMESTAMP),
  ('royalewithcheese','Royale With Cheese','http://p.hellyeah.org/', CURRENT_TIMESTAMP),
  ('rssdent','rssdent','http://github.com/zcopley/rssdent/tree/master', CURRENT_TIMESTAMP),
  ('rygh.no','rygh.no','http://rygh.no/', CURRENT_TIMESTAMP),
  ('ryghsms','ryghsms','http://sms.rygh.no/', CURRENT_TIMESTAMP),
  ('smob','SMOB','http://smob.sioc-project.org/', CURRENT_TIMESTAMP),
  ('socialoomphBfD4pMqz31', 'SocialOomph', 'http://www.socialoomph.com/', CURRENT_TIMESTAMP),
  ('spaz','Spaz','http://funkatron.com/spaz', CURRENT_TIMESTAMP),
  ('StatusNet Desktop', 'StatusNet Desktop', 'http://status.net/desktop', CURRENT_TIMESTAMP),
  ('StatusNet Mobile', 'StatusNet Mobile', 'http://status.net/mobile', CURRENT_TIMESTAMP),
  ('StatusNet iPhone', 'iPhone', 'http://status.net/iphone', CURRENT_TIMESTAMP),
  ('StatusNet Android', 'Android', 'http://status.net/android', CURRENT_TIMESTAMP),
  ('StatusNet Blackberry', 'Blackberry', 'http://status.net/blackberry', CURRENT_TIMESTAMP),
  ('tarpipe','tarpipe','http://tarpipe.com/', CURRENT_TIMESTAMP),
  ('tjunar','Tjunar','http://nederflash.nl/boek/titels/tjunar-air', CURRENT_TIMESTAMP),
  ('tr.im','tr.im','http://tr.im/', CURRENT_TIMESTAMP),
  ('triklepost', 'Tricklepost', 'http://github.com/zcopley/tricklepost/tree/master', CURRENT_TIMESTAMP),
  ('tweenky','Tweenky','http://beta.tweenky.com/', CURRENT_TIMESTAMP),
  ('TweetDeck', 'TweetDeck', 'http://www.tweetdeck.com/', CURRENT_TIMESTAMP),
  ('twhirl','Twhirl','http://www.twhirl.org/', CURRENT_TIMESTAMP),
  ('twibble','twibble','http://www.twibble.de/', CURRENT_TIMESTAMP),
  ('Twidge','Twidge','http://software.complete.org/twidge', CURRENT_TIMESTAMP),
  ('twidge','Twidge','http://software.complete.org/twidge', CURRENT_TIMESTAMP),
  ('twidroid','twidroid','http://www.twidroid.com/', CURRENT_TIMESTAMP),
  ('twittelator','Twittelator','http://www.stone.com/iPhone/Twittelator/', CURRENT_TIMESTAMP),
  ('twitter','Twitter','http://twitter.com/', CURRENT_TIMESTAMP),
  ('twitterfeed','twitterfeed','http://twitterfeed.com/', CURRENT_TIMESTAMP),
  ('twitterphoto','TwitterPhoto','http://richfish.org/twitterphoto/', CURRENT_TIMESTAMP),
  ('twitterpm','Net::Twitter','http://search.cpan.org/dist/Net-Twitter/', CURRENT_TIMESTAMP),
  ('twittertools','Twitter Tools','http://wordpress.org/extend/plugins/twitter-tools/', CURRENT_TIMESTAMP),
  ('twitux','Twitux','http://live.gnome.org/DanielMorales/Twitux', CURRENT_TIMESTAMP),
  ('twitvim','TwitVim','http://vim.sourceforge.net/scripts/script.php?script_id=2204', CURRENT_TIMESTAMP),
  ('Updating.Me','Updating.Me','http://updating.me/', CURRENT_TIMESTAMP),
  ('urfastr','urfastr','http://urfastr.net/', CURRENT_TIMESTAMP),
  ('yatca','Yatca','http://www.yatca.com/', CURRENT_TIMESTAMP),
  ('rss.me', 'rss.me', 'http://rss.me/', CURRENT_TIMESTAMP);
