INSERT INTO sms_carrier
  (id, name, email_pattern, created)
VALUES
  (100056, '3 River Wireless', '%s@sms.3rivers.net', CURRENT_TIMESTAMP),
  (100057, '7-11 Speakout', '%s@cingularme.com', CURRENT_TIMESTAMP),
  (100058, 'Airtel (Karnataka, India)', '%s@airtelkk.com', CURRENT_TIMESTAMP),
  (100059, 'Alaska Communications Systems', '%s@msg.acsalaska.com', CURRENT_TIMESTAMP),
  (100060, 'Alltel Wireless', '%s@message.alltel.com', CURRENT_TIMESTAMP),
  (100061, 'AT&T Wireless', '%s@txt.att.net', CURRENT_TIMESTAMP),
  (100062, 'Bell Mobility (Canada)', '%s@txt.bell.ca', CURRENT_TIMESTAMP),
  (100063, 'Boost Mobile', '%s@myboostmobile.com', CURRENT_TIMESTAMP),
  (100064, 'Cellular One (Dobson)', '%s@mobile.celloneusa.com', CURRENT_TIMESTAMP),
  (100065, 'Cingular (Postpaid)', '%s@cingularme.com', CURRENT_TIMESTAMP),
  (100066, 'Centennial Wireless', '%s@cwemail.com', CURRENT_TIMESTAMP),
  (100067, 'Cingular (GoPhone prepaid)', '%s@cingularme.com', CURRENT_TIMESTAMP),
  (100068, 'Claro (Nicaragua)', '%s@ideasclaro-ca.com', CURRENT_TIMESTAMP),
  (100069, 'Comcel', '%s@comcel.com.co', CURRENT_TIMESTAMP),
  (100070, 'Cricket', '%s@sms.mycricket.com', CURRENT_TIMESTAMP),
  (100071, 'CTI', '%s@sms.ctimovil.com.ar', CURRENT_TIMESTAMP),
  (100072, 'Emtel (Mauritius)', '%s@emtelworld.net', CURRENT_TIMESTAMP),
  (100073, 'Fido (Canada)', '%s@fido.ca', CURRENT_TIMESTAMP),
  (100074, 'General Communications Inc.', '%s@msg.gci.net', CURRENT_TIMESTAMP),
  (100075, 'Globalstar', '%s@msg.globalstarusa.com', CURRENT_TIMESTAMP),
  (100076, 'Helio', '%s@myhelio.com', CURRENT_TIMESTAMP),
  (100077, 'Illinois Valley Cellular', '%s@ivctext.com', CURRENT_TIMESTAMP),
  (100078, 'i wireless', '%s.iws@iwspcs.net', CURRENT_TIMESTAMP),
  (100079, 'Meteor (Ireland)', '%s@sms.mymeteor.ie', CURRENT_TIMESTAMP),
  (100080, 'Mero Mobile (Nepal)', '%s@sms.spicenepal.com', CURRENT_TIMESTAMP),
  (100081, 'MetroPCS', '%s@mymetropcs.com', CURRENT_TIMESTAMP),
  (100082, 'Movicom', '%s@movimensaje.com.ar', CURRENT_TIMESTAMP),
  (100083, 'Mobitel (Sri Lanka)', '%s@sms.mobitel.lk', CURRENT_TIMESTAMP),
  (100084, 'Movistar (Colombia)', '%s@movistar.com.co', CURRENT_TIMESTAMP),
  (100085, 'MTN (South Africa)', '%s@sms.co.za', CURRENT_TIMESTAMP),
  (100086, 'MTS (Canada)', '%s@text.mtsmobility.com', CURRENT_TIMESTAMP),
  (100087, 'Nextel (Argentina)', '%s@nextel.net.ar', CURRENT_TIMESTAMP),
  (100088, 'Orange (Poland)', '%s@orange.pl', CURRENT_TIMESTAMP),
  (100089, 'Personal (Argentina)', '%s@personal-net.com.ar', CURRENT_TIMESTAMP),
  (100090, 'Plus GSM (Poland)', '%s@text.plusgsm.pl', CURRENT_TIMESTAMP),
  (100091, 'President''s Choice (Canada)', '%s@txt.bell.ca', CURRENT_TIMESTAMP),
  (100092, 'Qwest', '%s@qwestmp.com', CURRENT_TIMESTAMP),
  (100093, 'Rogers (Canada)', '%s@pcs.rogers.com', CURRENT_TIMESTAMP),
  (100094, 'Sasktel (Canada)', '%s@sms.sasktel.com', CURRENT_TIMESTAMP),
  (100095, 'Setar Mobile email (Aruba)', '%s@mas.aw', CURRENT_TIMESTAMP),
  (100096, 'Solo Mobile', '%s@txt.bell.ca', CURRENT_TIMESTAMP),
  (100097, 'Sprint (PCS)', '%s@messaging.sprintpcs.com', CURRENT_TIMESTAMP),
  (100098, 'Sprint (Nextel)', '%s@page.nextel.com', CURRENT_TIMESTAMP),
  (100099, 'Suncom', '%s@tms.suncom.com', CURRENT_TIMESTAMP),
  (100100, 'T-Mobile', '%s@tmomail.net', CURRENT_TIMESTAMP),
  (100101, 'T-Mobile (Austria)', '%s@sms.t-mobile.at', CURRENT_TIMESTAMP),
  (100102, 'Telus Mobility (Canada)', '%s@msg.telus.com', CURRENT_TIMESTAMP),
  (100103, 'Thumb Cellular', '%s@sms.thumbcellular.com', CURRENT_TIMESTAMP),
  (100104, 'Tigo (Formerly Ola)', '%s@sms.tigo.com.co', CURRENT_TIMESTAMP),
  (100105, 'Unicel', '%s@utext.com', CURRENT_TIMESTAMP),
  (100106, 'US Cellular', '%s@email.uscc.net', CURRENT_TIMESTAMP),
  (100107, 'Verizon', '%s@vtext.com', CURRENT_TIMESTAMP),
  (100108, 'Virgin Mobile (Canada)', '%s@vmobile.ca', CURRENT_TIMESTAMP),
  (100109, 'Virgin Mobile (USA)', '%s@vmobl.com', CURRENT_TIMESTAMP),
  (100110, 'YCC', '%s@sms.ycc.ru', CURRENT_TIMESTAMP),
  (100111, 'Orange (UK)', '%s@orange.net', CURRENT_TIMESTAMP),
  (100112, 'Cincinnati Bell Wireless', '%s@gocbw.com', CURRENT_TIMESTAMP),
  (100113, 'T-Mobile Germany', '%s@t-mobile-sms.de', CURRENT_TIMESTAMP),
  (100114, 'Vodafone Germany', '%s@vodafone-sms.de', CURRENT_TIMESTAMP),
  (100115, 'E-Plus', '%s@smsmail.eplus.de', CURRENT_TIMESTAMP),
  (100116, 'Cellular South', '%s@csouth1.com', CURRENT_TIMESTAMP),
  (100117, 'ChinaMobile (139)', '%s@139.com', CURRENT_TIMESTAMP),
  (100118, 'Dialog Axiata', '%s@dialog.lk', CURRENT_TIMESTAMP);
